# Generated by Django 3.1.12 on 2022-05-06 18:58

from django.db import migrations, models
import django.db.models.deletion
import media.models
import sqlalchemy.sql.expression


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user_auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MediaCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(verbose_name='Created On')),
                ('updated', models.DateTimeField(verbose_name='Updated On')),
                ('is_active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
            ],
            options={
                'verbose_name': 'Media Category',
                'verbose_name_plural': 'Media Categories',
                'db_table': 'Media_Category',
            },
        ),
        migrations.CreateModel(
            name='MediaType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created', models.DateTimeField(verbose_name='Created On')),
                ('updated', models.DateTimeField(verbose_name='Updated On')),
                ('is_active', models.BooleanField(default=sqlalchemy.sql.expression.true)),
            ],
            options={
                'verbose_name': 'Media Type',
                'verbose_name_plural': 'Media Types',
                'db_table': 'Media_Type',
            },
        ),
        migrations.CreateModel(
            name='MediaItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('path', models.FileField(upload_to=media.models.user_directory_path)),
                ('size', models.BigIntegerField()),
                ('created_on', models.DateTimeField(verbose_name='Created On')),
                ('updated_on', models.DateTimeField(verbose_name='Updated On')),
                ('Created By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.user')),
                ('Updated By', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='user_auth.user')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediacategory')),
                ('type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='media.mediatype')),
            ],
            options={
                'verbose_name': 'Media Item',
                'verbose_name_plural': 'Media Items',
                'db_table': 'Media_Item',
            },
        ),
    ]
