# Generated by Django 3.1.12 on 2022-05-06 19:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediacategory',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='updated_on',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated On'),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='created',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Created On'),
        ),
        migrations.AlterField(
            model_name='mediatype',
            name='updated',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='Updated On'),
        ),
    ]
