# Generated by Django 3.1.12 on 2022-05-09 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0002_auto_20220507_0037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='size',
            field=models.BigIntegerField(null=True),
        ),
    ]
