# Generated by Django 3.1.12 on 2022-05-09 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0003_auto_20220509_1220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaitem',
            name='size',
            field=models.BigIntegerField(default=0),
        ),
    ]
